### ISSUE TITLE
Building historical_capacity where not defined should not be allowed

### ISSUE THREAD

**Issue by ClaraLuisa** [iiasa/message_ix#119]
![image](https://user-images.githubusercontent.com/16190366/47139033-2c5fe700-d2bb-11e8-8341-4b79ac16eed7.png)

When a input/output combination is defined for historical vintage years of a technology but no hist_new_cap is defined for all the historical vintage combinations, the model is not restricted to the CAPACITY_MAINTENANCE_HIST bound. This can lead to capacity beeing built where not allowed (as in the picture)

**Comment by ClaraLuisa** [comment]
...also, a historical_new_capacity of 0 can not be added to the model as it is not passed on to the gdx (either GAMS or DB issue)

**Comment by glatterf42** [comment]
I'm going to close this issue as it seems outdated. 
We discussed the issue in today's weekly meeting and it was suggested that it is not only possible to set `historical_new_capacity` to 0, this is even the default, i.e. if you don't define any `historical_new_capacity > 0`, the model will not build any. Values of `0` might be hidden in the `.gdx` file, though, which could explain why they didn't show up.
I confirmed this through quick experimentation with the [historical_new_capacity tutorial](https://github.com/iiasa/message_ix/blob/main/tutorial/westeros/westeros_historical_new_capacity.ipynb): it is possible to set the parameter to 0 and removing it entirely has the same effect. 
As for the other part of this issue, it was suggested that this is a usage error: `historical_new_capacity` should be defined for all historical years. This definition can happen through the default value, though, so I'm not sure what the issue refers to precisely. Maybe six years ago, it was indeed not possible to pass 0 and no such default was set. 

So please, if this issue is still relevant, open a new issue (linking to this one if you please) and provide the steps you use to set up your model, one by one, so that we could reproduce and study the error.
