### ISSUE TITLE
Install from source copies all gdx files

### ISSUE THREAD

**Issue by danielhuppmann** [iiasa/message_ix#141]
Installing from source copies all gdx files from the cloned folder to the installed location, which is a pain if you have run large model instances previously.

**Comment by khaeru** [comment]
In #214, @OFR-IIASA reported that:
- This was experienced with `pip install .` but *not* with `python setup.py install`.
- It can cause the install to fail if there are enough GDX files that disk space is exhausted.

IMO, there are two issues here that can be addressed by separate fixes.
1. **Packaging.** setup.py should explicitly exclude GDX files anywhere in the tree from (I believe) the package_data argument, so that they are not packaged or installed. Fix this in message_ix.
2. **Separation of code and data.** Input and output GDX files should never be placed in the same directory as the code. If, for example, a user has a system install of message_ix, this location would not be writeable. Instead, the files should be kept in a temporary directory and/or a configurable directory—defaulting to the current directory or something like `$XDG_DATA_HOME/ixmp/model/MESSAGE/`. The fix for this might touch both ixmp and message_ix.

**Comment by danielhuppmann** [comment]
the "copying of gdx files" for `setup.py` was fixed in #181

**Comment by danielhuppmann** [comment]
> 2. Separation of code and data

One consideration: for debugging of the GAMS code, it is often helpful to execute GAMS from GAMS Studio (or GAMS IDE). For this reason, there is the file `MESSAGE_master.gms` where a user can set which `gdx` file to use, whether to use MACRO, extended calibration info, activation of relaxations for constraints, ...

Moving the `gdx` files out of that folder might complicate that if the ' data directory' is only known from Python.

**Comment by khaeru** [comment]
> the "copying of gdx files" for `setup.py` was fixed in #181

I am a bit mystified as to why it happens with one but not the other, as `pip` uses `setup.py` internally.

> there is the file `MESSAGE_master.gms` where a user can set which `gdx` file to use, whether to use MACRO, extended calibration info, activation of relaxations for constraints, ...

Do you mean `MESSAGE_run.gms`? AFAICT it sets defaults for the compile-time `in` and `out` variables. The change I described above wouldn't alter this, but simply provide other paths for these variables that are outside the code directory, when run through the Python/R API.

**Comment by danielhuppmann** [comment]
No, I mean `MESSAGE_master.gms` (this is probably copied and renamed from the `templates` folder only on Windows by `install.bat`, sorry).

This file calls `MESSAGE_run.gms` or `MESSAGE_MACRO_run.gms` and allows to set `in` and `out` (and other settings) in a simple way from within GAMS Studio or GAMS IDE. And if GAMS doesn't know the data directory path, this will make GAMS code development more of a pain.

**Comment by khaeru** [comment]
`message-ix copy-model` has been rewritten and now excludes .gdx files: https://github.com/iiasa/message_ix/blob/760e8dfbb145fd397253d552f5cbb143cfe2f2d7/message_ix/cli.py#L30-L43
