### ISSUE TITLE
rendering of MESSAGEix documentation on Firefox and EDGE

### ISSUE THREAD

**Issue by volker-krey** [iiasa/message_ix#157]
In Firefox and EDGE the MESSAGEix documentation (public version at http://messageix.iiasa.ac.at) theme renders using an italics font which is difficult to read (screenshot from Firefox attached). Making sure that the theme renders the same across browsers (in a more readable way than the attached example) would be good.

![messageix_screenshot](https://user-images.githubusercontent.com/17138117/51969742-7e490900-2475-11e9-96ba-4a226bfcd6f5.png)

**Comment by khaeru** [comment]
The docs seem to use files committed to the message_ix repo under `doc/source/_theme`, originally from here: https://github.com/kennethreitz-archive/kr-sphinx-themes

The original is ~7 years old, and it is probably browser changes since then that have broken its font specifications. [Flask itself](http://flask.pocoo.org/docs/1.0/) now uses [this theme](https://github.com/pallets/flask-sphinx-themes). We could update to that, or the [ReadTheDocs theme](http://www.writethedocs.org/guide/tools/sphinx-themes/) or another.

**Comment by gidden** [comment]
+1 for changing the theme to something better maintained. I believe this
was an old theme I used 5+ years ago for another project and just plugged
in here because the others didn't quite look as nice. So timing seems to
fit =)

**Comment by khaeru** [comment]
Closed by #154.
