### ISSUE TITLE
Installing Message on Linux

### ISSUE THREAD

**Issue by fkanyako** [iiasa/message_ix#184]
Hi,

We are installing message via Anaconda using the instructions available at (https://messageix.iiasa.ac.at/getting_started.html). 
At step 6:  "Open a command prompt in the message_ix directory and type: $ pip install ".
We are getting an error: "Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found."

We do not understand what step 6 is trying to accomplish or what this error means. Can you provide some clarifications?

Regards

**Comment by khaeru** [comment]
Hi @fkanyako!

To be clear, there are two ways to install MESSAGE:

A. *via Anaconda*:
 - Perform steps 1 and 2 in the "Install GAMs" section.
 - Perform steps 3, 4, and 5 in the "Install MESSAGEix *via Anaconda*" section.
 - Done (i.e. there is no step 6 or 7).

B. *from source*:
 - Perform steps 1 and 2 in the "Install GAMs" section.
 - Perform steps 3, 4, 5, 6, and 7 in the "Install MESSAGEix *from source*" section. (i.e. skip over the "…via Anaconda" section entirely.)
 - Done.

Since you say both "via Anaconda" and "step 6", I'm wondering if you did (A) and then jumped straight to step 6 from (B). This definitely would not work, and might produce the error you are seeing.

**Comment by fkanyako** [comment]
Thank you, I installed via Anaconda:
A. via Anaconda:
Perform steps 1 and 2 in the "Install GAMs" section.
Perform steps 3, 4, and 5 in the "Install MESSAGEix via Anaconda" section.
Then I jumped to step 6 from B. So maybe that was the problem.

So how do I check if I installed correctly using A. via Anaconda then? How to test the model?

Thank you again.

**Comment by gidden** [comment]
Hi @fkanyako you can start testing out the modeling framework using the [tutorials](https://messageix.iiasa.ac.at/tutorials.html) after installing from Anaconda. If you think the installation instructions could be clearer, please feel free to issue a PR! I'll close the issue for now, but let us know if you run into any other issues.
