### ISSUE TITLE
plotting problem

### ISSUE THREAD

**Issue by sinahp1372** [iiasa/message_ix#194]
I have installed all packages for tutorials but when I run the code for Austrian energy system the plotting part has an error saying : 
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-31-a85f3b67ef13> in <module>
----> 1 from tools import Plots
      2 p = Plots(scenario, country)

ModuleNotFoundError: No module named 'tools'
I have checked the module tools is available in the code

**Comment by gidden** [comment]
Hi @sinahp1372, thanks for making an issue! The problem here is that there is a `tools.py` file in the `tutorial` folder, which is being imported here. It *assumes* that you are in the tutorial folder in order to do the import. 

In your jupyter notebook, you can type `pwd` in a cell which should show you your "present working directory". If that is **not** the same as the tutorial folder, then we have found the problem.

In order to fix this in the short term, you may need to start the Jupyter Notebook from that directory. You can do some from the Anaconda Prompt, by navigating to the directory first, then typing `jupyter notebook` in the prompt.

However, I think there is a better solution here - which is to put the tutorial-related tools directly in the `message_ix` install. Would you mind making an issue stating that this should be done?

**Comment by sinahp1372** [comment]
Dear @gidden the short term method works properly but the last recomendation  does not apply I tried copying it in both  messageix tools folder and message master folder 
thanks for your help

**Comment by gidden** [comment]
ok, great, thanks!
