### ISSUE TITLE
cplex.opt issues when running two scenarios in parallel

### ISSUE THREAD

**Issue by OFR-IIASA** [iiasa/message_ix#222]
cplex.opt is generated when starting a run and subsequently erased.

If two scenarios are run in parallel, this results in the following error:

>  File "c:\repo\message_ix\message_ix\core.py", line 366, in solve
>     os.remove(fname)
> FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Repo\\message_ix\\message_ix\\model\\cplex.opt'

The reason I believe is because scenario1 creates a cplex.opt file - the scenario is then run.
Then scenario2 creates a new cplex.opt file - the scenario is run.
Scenario1 finishes and deletes the cplex.opt file
Scenario2 finishes and wants to delete a file which doesnt exist.

**Comment by khaeru** [comment]
This is the same as iiasa/ixmp#163.

**Comment by khaeru** [comment]
- This was just re-reported as #338.
- #250 is chronologically later but contains more discussion.
- On reconsideration, both usage reports (from @tzipperle and @OFR-IIASA) seem to indicate that the model solves without issue *using the same files in the same directory*; the only problem seems to be during this clean-up of the options file.
- This is a little puzzling to me—e.g. what are the names of the ≥2 .lst files created by the concurrent runs?
- …but, at least it means the fix is simple.
