### ISSUE TITLE
links from MESSAGE tutorial to v1.1.0 instead of v1.2

### ISSUE THREAD

**Issue by Ruslana22** [iiasa/message_ix#225]
In the online tutorial https://message.iiasa.ac.at/en/stable/tutorials.html
the all the hyperlinks connect to the old version:
https://github.com/iiasa/message_ix/blob/v1.1.0/tutorial/...
instead of v1.2.0

**Comment by khaeru** [comment]
@Ruslana22 good catch, thank you! cc: @gidden @danielhuppmann

1. For the future, this is something that we should add to our [release procedure](https://github.com/iiasa/message_ix/wiki/Release-procedure).
2. For now, we should:
   - establish a bugfix/maintenance branch (`v1.2.x` or similar) from an appropriate commit,
   - fix this issue,
   - ensure the RTD `stable` pointer is towards the tip of this branch, rather than the `v1.2.0` tag.

**Comment by khaeru** [comment]
Closed via #228.
