### ISSUE TITLE
Improving Westeros tutorials - experiences from new users

### ISSUE THREAD

**Issue by jkikstra** [iiasa/message_ix#245]
Based on running through the tutorials, I made a small overview of the things that I've bumped into that could/should be changed to make the Westeros tutorials a bit clearer. @GamzeUnlu95 @fabiosferra @francescolovat you are invited to add your points here as well, if any.

Overall:

- Add order: the python notebook tutorials are to be run in a specific order, but this is not specified.

- Like Westeros_seasonality: add some general things to all other Notebooks: A) email address/developer, B) requirements for running [connected to previous point], C) 

Emission Taxes & Bounds:

- Especially for Taxes: specify more clearly how `'value': emission_prices.set_index('year').loc[[700, 710, 720]].lvl` works

Firm Capacity: 

- rating and reliability --> Ensuring enough Firm Capacity
	- a typo (independet)
	- The values in the code are not the same as the ones in the descriptive test.
	- the descriptive text itself is not clear: 20%, 80%, remaining 90%(?) 5%

Flexible Generation:

- Add a carbon tax
	- unit of emission factor should probably not be USD/GWa but rather something with GtCO2, e.g.

- Describing the Renewable Technologies  Flexibility --> Flexibility of demand and supply
	- description: why the formulation of "wind 5% demand" and "coal 20% provide"
	- where do the numbers (ratings) come from?
	
N.B. someone will be assigned for updating the notebooks once all feedback has been collected here.

**Comment by francescolovat** [comment]
So, @khaeru, here most of the comments have already been addressed in #247. However, still remains unclear:
-  the section **Describing flexibility requirements** in `westeros_flexible_generation.ipynb`. I think it is close related with the section **Reliability of Power System** in `westeros_firm_capacity.ipynb` due to the rating of wind farms. In the latter there is a great description in a markdown cell, which lacks in the former notebook. Somebody should account for this (@jkikstra @GamzeUnlu95 @fabiosferra).
- that the notebooks are to be run in a specific order (not specified).
- in `westeros_emissions_taxes.ipynb` a small comment would be needed to explain what `value': emission_prices.set_index('year').loc[[700, 710, 720]].lvl` exactly does.

After dealing with these, I think this issue can be closed.

**Comment by jkikstra** [comment]
Completed by #284 .
