### ISSUE TITLE
Improving Austrian Energy System tutorials - experiences from new users

### ISSUE THREAD

**Issue by jkikstra** [iiasa/message_ix#246]
Overall:
- Add order: the python notebook tutorials are to be run in a specific order, but this is not specified.
- 

austria.ipynb:
- when adding spatial detail: add a sentence showing what this command would look like if you are adding multiple countries/adding a full spatial set.
- economic parameters: 
	- if the value is 0.05, the unit should be '-', rather than '%'
	- add some explanation about 'beta' == macro relation between gdp growth and energy demand (demand flexibility)?
- technologies:
	- check units: be more clear about the input data units from IEA statistics: if this is really demand per year, then why are you dividing by 8760?
- Engineering Parameters:
	- for inputs (and outputs): if the values are 1.0 and 0.3, the unit should be '-', rather than '%' ==> explanation of what these values represent (as a comment, e.g. # efficiency) wouldn't hurt 
	- already here add explanation: why are both 'bulb' and 'cfl' here?
	- counterintuitive: why is 'import' modelled as an output, rather than an input => perhaps add explanation on how import is outputting to add to the energy of the system, and can be an input to other technologies after that?
	- again, for capacity factor, change unit from '%' to '-'
- Technoeconomic Parameters:
	- should the unit of investment cost (base_inc_cost) change to 'USD'?
	- base_var_cost and base_fix_cost should be in the same units; its value should probably be muliplied by the same number as well (unless the input units are different - if this is the case, that should be clarified)
- Dynamic Behavior Parameters:
	- base_growth & base_initial: change '%' to '-'
	- what is base_initial? ==> add explanation
	- add notes/explanation that both lower and upper bound activity are first set to be the same in this simplified energy system model

_To be updated with more comments on the other tutorial ipynb files_

**Comment by GamzeUnlu95** [comment]
I also encountered some of the issues above. To complement the comments above: 

- In techno-economic parameters for investment and fixed costs the unit is mentioned as USD/GWa. But for investment and fixed costs the unit is USD/GW in the calculation which is correct. For variable cost, the unit specified looks correct and consistent with the calculation (USD/GWa). 

- Some parameters and how they are used/calculated can be more clear such as: initial_activity_up, bound_new_capacity_up; bound_activity_up and bound_activity_lo in Dynamic Behavior Parameters Section.

**Comment by francescolovat** [comment]
Hi all! So I've also went through the `austria.ipynb` and I'll recap the problems I'll include in the PR including yours @jkikstra @GamzeUnlu95  :

1. Gamze's comments: I agree with both your bullets. I'll change the units according to the baseline scenario
2. Jarmo's comments: I agree with all comments except from the one on the "data units from IEA statistics". **They are correct** since the unit in MESSAGEix is GWa = 8760 GWh and the units from the IEA are just in GWh, which then needs to be divided by 8760 to get MESSAGEix units. Var and Fix O&M have the same units but they don't really represent the same concept. I'll explain it as I did for the Westeros tutorial. Finally, in regards of " 'import' modelled as an output, rather than an input", that is usually how it is designed in most of the models (also in TIMES-MARKAL): **the imported quantity is the result/output of the "technology" import.**

**Comment by GamzeUnlu95** [comment]
Some additions from the rest of the notebooks to the points mentioned above. 

- _In Austria Load Scenario_ the purpose of the following line was not clear to me:
tools.check_local_model(model, 'austria.ipynb')

- _In Investigating Many Policy Scenario_ there is the same issue with the units of the investment cost (it should be USD/GW instead of USD/GWa?). 

- I couldn't find a description of the methods of the Tools package such as read_scenario in the documentation. Does it also solve the updated scenario in the example as I couldn't see where the new_scen is solved?

**Comment by francescolovat** [comment]
So, @khaeru, here most of the comments have already been addressed in #248. However, still remains unclear in `austria.ipynb`:
- that the notebooks are to be run in a specific order (not specified).
- the section **Economic parameters**. Some explanation about `demand  = gdp ** beta` (relation between gdp growth and energy demand) and their values should be included. Somebody should account for this (@jkikstra @GamzeUnlu95 @fabiosferra).
- what's the difference between the parameters `initial_activity_up` and `growth_activity_up` (some explanation needed needed). I guess `growth_activity_up` is the annual increase in production by the list of technologies in `growth_technologies` (including **cfl** and **bulb**). However, then a different value is assigned again to **clf** and **bulb** and saved into the parameter `initial_activity_up`. Why two different parameters created from **lights** if they are defined the same way?
- the difference between `initial_activity_up`, `bound_new_capacity_up` and `bound_activity_up`. Add a further comment in `austria.ipynb` to explain it.

After dealing with these, I think this issue can be closed.

**Comment by khaeru** [comment]
> After dealing with these, I think this issue can be closed.

Am I right in understanding that #288 polished off these last few items? If so, please do close this issue.
