### ISSUE TITLE
'JDBCBackend' object has no attribute 'get_cat_list'

### ISSUE THREAD

**Issue by francescolovat** [iiasa/message_ix#293]
When I was trying to print the list of all categories for the set _'year'_ for a specific scenario using the method **_cat_list_** in `/message_ix/core.py` I've encountered the following error in _JDBCBackend_:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-1301981865b5> in <module>
      4 scenario.set('cat_year')
      5 scenario.cat('year', 'firstmodelyear')
----> 6 scenario.cat_list('year')

c:\users\lovat\documents\github\francescolovat\message_ix\message_ix\core.py in cat_list(self, name)
    157             Name of the set.
    158         """
--> 159         return self._backend('get_cat_list', name)
    160 
    161     def add_cat(self, name, cat, keys, is_unique=False):

c:\users\lovat\documents\github\francescolovat\ixmp\ixmp\core.py in _backend(self, method, *args, **kwargs)
    356     def _backend(self, method, *args, **kwargs):
    357         """Convenience for calling *method* on the backend."""
--> 358         return self.platform._backend(self, method, *args, **kwargs)
    359 
    360     # functions for platform management

c:\users\lovat\documents\github\francescolovat\ixmp\ixmp\backend\base.py in __call__(self, obj, method, *args, **kwargs)
     23         for the method name, e.g. 'ts_{method}'.
     24         """
---> 25         return getattr(self, method)(obj, *args, **kwargs)
     26 
     27     def close_db(self):  # pragma: no cover

AttributeError: 'JDBCBackend' object has no attribute 'get_cat_list'
```

I don't know exactly how to handle this issue.

**Comment by khaeru** [comment]
@francescolovat good catch! Thanks for filing this. The Backend method is named `cat_list`, not `get_cat_list`:

https://github.com/iiasa/ixmp/blob/39e900dea02950bcea69e273e79002b5748551b4/ixmp/backend/base.py#L715-L717

https://github.com/iiasa/ixmp/blob/39e900dea02950bcea69e273e79002b5748551b4/ixmp/backend/jdbc.py#L674-L675

Can you please…
1. Modify the issue description to use a literal block with triple backticks (`) instead of a screenshot image? Images are not searchable.
2. Create a new branch named `issue/293` and add a minimal test that triggers this error; and
3. Make a PR from that branch?

(3) will be the starting point for someone (not necessarily you or I) to fix the issue.

**Comment by francescolovat** [comment]
Hi @khaeru thanks for your quick reply! I'll do that now!
