### ISSUE TITLE
launching ixmp.Platform using config file at 'None'

### ISSUE THREAD

**Issue by github-wbx** [iiasa/message_ix#305]
Dear author,
  I'm trying to run the "Westeros Electrified" model following the supported tutorial, and GAMS, Anaconda, and Message-ix have installed. Here is a problem that the code "mp = ixmp.Platform()"  does not work, it always points out aunching ixmp.Platform using config file at 'None'(See attached picture). I hope you can give me a hand to figure it out, and look forward to your reply!
![QQ截图20200202101437](https://user-images.githubusercontent.com/60533517/73601924-05f3b700-45a5-11ea-9dbb-f6590c236146.png)

**Comment by khaeru** [comment]
It seems you are running an outdated version of ixmp. Can you please upgrade to the latest version of ixmp and message_ix and try again?

**Comment by github-wbx** [comment]
Thank you for your reply. I cannot find a way to upgrade the latest version of ixmp and message_ix from the Installation and Tutorials, or maybe I missed some tips and information. I appreciate  you can  provide some more detail information about how to upgrade the latest version, and it's better that give some suggestions for new users in practice.

**Comment by ClaraLuisa** [comment]
> Thank you for your reply. I cannot find a way to upgrade the latest version of ixmp and message_ix from the Installation and Tutorials, or maybe I missed some tips and information. I appreciate you can provide some more detail information about how to upgrade the latest version, and it's better that give some suggestions for new users in practice.

hey! If you installed message_ix and ixmp via Anaconda (as recommended), simply open your anaconda command prompt and type: `conda update ixmp`.  Then you should be good to go!

**Comment by github-wbx** [comment]
Thank you, Clara. I typed : conda install -c conda-forge message-ix and conda update ixmp in the anaconda command prompt, and the result showed all requested package already installed, but the code  "mp = ixmp.Platform()" still does not work(See attached picture )
![1](https://user-images.githubusercontent.com/60533517/73733672-591d6380-4777-11ea-8b9a-f6317838da21.png)
![2](https://user-images.githubusercontent.com/60533517/73733673-591d6380-4777-11ea-8c56-974797d45b88.png)

**Comment by khaeru** [comment]
>  the code "mp = ixmp.Platform()" still does not work(See attached picture )

The picture shows that you still are running code from an older version of ixmp, and have not successfully upgraded to the latest version.

When using Python (including packages like message_ix and ixmp), it is essential to learn how to use the package manager for one's system—either conda, pip, or something else. You are correct that we should mention in the documentation that this is pre-requisite knowledge, and provide links in case people have trouble to find it on their own.

Since you are using Conda, the documentation is here: https://conda.io/en/latest/
Here is the documentation of how to manage packages: https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html

In particular:

- `conda install --channel conda-forge message-ix` will install message-ix *if it is not already already installed*. It will not update an existing package or the dependencies of that package.
- `conda update ixmp` is unlikely to work because you did not specify `--channel conda-forge`.

Here is the description of how to list installed packages: https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#viewing-a-list-of-installed-packages
Once you successfully upgrade, it should show that you have ixmp 2.0.0 and message_ix 2.0.0 installed. Please include the output of this command with your next comment!

**Comment by github-wbx** [comment]
Thank you for your suggestions. I have successfully upgraded the packages of message_ix and ixmp to the latest version(See attached picture). However, new problems appeared after running the code, it showed that "RuntimeError: unhandled Java exception: Unable to obtain Jdbc connection from DataSource"(See attached picture ). The paper of "The MESSAGEix Integrated Assessment Model and the ix modeling platform(ixmp)An open framework for integrated and cross-cutting analysis of energy, climate, the environment, and sustainable development" pointed out that the core component of the ix modeling platform is a Java Virtual Machine to manage the connection to an underlying database instance and retrieve or edit data, but do not give more information to operate with Java. I hope you can continue to give me some help to solve the problem. Looking  forward to your reply.
![ix](https://user-images.githubusercontent.com/60533517/75255037-464cfa80-581c-11ea-81d3-b02e244ab1f9.png)
![message](https://user-images.githubusercontent.com/60533517/75255048-4c42db80-581c-11ea-9954-b37c13040841.png)
![running results1](https://user-images.githubusercontent.com/60533517/75255056-51a02600-581c-11ea-906d-64b9ef5d293a.png)
![running results2](https://user-images.githubusercontent.com/60533517/75255070-57960700-581c-11ea-84e1-d6f687db6e5c.png)

**Comment by awais307** [comment]
Hi,  It seems that this issue is not related to ixmp. I will suggest reinstalling everything (python, anaconda and relevant packages). Also, please make sure that the environment variables are properly set in your system. Also please look onto the discussion in [issue#35](https://github.com/iiasa/message_ix/issues/35) for proper installation of JAVA related tools.
