### ISSUE TITLE
PRICE_EMISSION is empty if the cumulative bound_emission is set

### ISSUE THREAD

**Issue by Chocooto** [iiasa/message_ix#334]
If I set a cumulative bound_emisssion, e.g. 
![image](https://user-images.githubusercontent.com/3286277/79542496-58317800-80be-11ea-9b2a-0805b46db44e.png)
the solved PRICE_EMISSION is empty.
But if I set the bound_emission year by year, e.g.
![image](https://user-images.githubusercontent.com/3286277/79542915-18b75b80-80bf-11ea-8e3e-74f4b0d6a2a3.png)
the solvel PRICE_EMISSION is as following.
![image](https://user-images.githubusercontent.com/3286277/79543062-616f1480-80bf-11ea-9815-0f7a3ebcd60d.png)
Could anyone explain why? The mechanisms to obtain the PRICE_EMISSION? What can influence PRICE_EMISSION? Thanks!

**Comment by behnam-zakeri** [comment]
Thanks @Chocooto for opening this issue. PRICE_EMISSION is the shadow price, derived from _marginal_ of EMISSION_CONSTRAINT equation (please see [this equation](https://github.com/iiasa/message_ix/blob/a14b6eca68c2ed1b0c7fc53ac2a95c16bb24c70a/message_ix/model/MESSAGE/model_solve.gms#L55) in `model_solve.gms`).
So, as the first step, can you check your output GDX to see if you have _marginal_ in the equation EMISSION_CONSTRAINT?

**Comment by Chocooto** [comment]
Thanks for responsing to this issue. I checked the EMISSION_CONSTRAINT (shown as following picture) in the output GDX, and I don't think there is _marginal_ in the equation.
![image](https://user-images.githubusercontent.com/3286277/79929172-8bd22080-8477-11ea-8f98-d38c825842bf.png)

**Comment by behnam-zakeri** [comment]
Thanks for checking this. So, having no _Marginal_ in EMISSION_CONSTRAINT can be due to different reasons:
- the cumulative bound is not binding, e.g., the cumulative emission is 200 and the added bound is 300. In fact, the bound doesn't pose any additional constraint to the system.
- or there are free-cost technologies that can reduce emissions, i.e., constraint on emissions don't have any additional cost to the system.

Based on the screenshot you shared above, it seems that the level of emissions (_Level_ ) stands exactly at the upper bound (_Upper_). So, the bound seems to be working. As the next step, can you check the equation EMISSION_EQUIVALENCE in your output GDX and see if you see any _Marginal_ for this emission type there? Because this equation indicates the simplified, yearly level of emissions, i.e., not considering cumulation caculations.

**Comment by Chocooto** [comment]
Thanks for explaining all the details! I checked the EMISSION_EQUIVALENCE in the output GDX and could see Marginal for "TCE and all" emission type as shown in the following figure. "EPS" is shown in the Marginal column for all the other emission types.
![image](https://user-images.githubusercontent.com/3286277/79976391-1b56ee00-84cf-11ea-99b1-5663a6bd8111.png)

**Comment by behnam-zakeri** [comment]
Thanks! here we only focus on `type_emission=TCE` and `type_tec=all`, because you have _bound_emission_ defined for them.
So, we do see _Marginal_ in this equation. This means that if we would want to reduce one unit of this emission type in any model **year**, there will be additional cost to the system. And additional cost means shadow price or price for this emission. But why we don't see a price in the **cumulative** mode, coming from _Marginal_ of EMISSION_CONSTRAINT.
Next, you need to make sure you have defined _cumulative_ years and _historical_emission_ correctly. You can see cumulative years in set _cat_year_. Make sure the years that are labeled as cumulative are the ones that you want to calculate the cumulative bound over them. Your model results show that your first model year is 2030. Are your cumulative years from 2030 or earlier? If earlier, you must have _historical_emission_ for them.

**Comment by Chocooto** [comment]
Thanks! I still have two questions.
1. My cumulative years start from 2020, so I added historical_emission as following.
![image](https://user-images.githubusercontent.com/3286277/79983149-ed2adb80-84d9-11ea-9221-58f2439aa09a.png)
But still no value shown in the PRICE_EMISSION...
2. You mean the Marginal value in the EQUIVALENCE is the carbon price? The carbon price remains the same as 15.4 from 2030 to 2110?

**Comment by behnam-zakeri** [comment]
1. It may be more straightforward to you remove 2020 from cumulative years in _cat_year_), and if needed, reduce the cumulative budget for the model years (period of 2030-2110).
2. No, _Marginal_ in EMISSION_EQUIVALENCE is not emission price, but showing undiscounted additional cost of the system per year if one more unit of that emission type. Emission prices are taken from _Marginal_ of EMISSION_CONSTRAINT, divided by discount factor (please refer to [this equation](https://github.com/iiasa/message_ix/blob/a14b6eca68c2ed1b0c7fc53ac2a95c16bb24c70a/message_ix/model/MESSAGE/model_solve.gms#L58)).
You can remove 2020 from cumulative years by `Scenario.remove_set()`:
`extra = scenario.set('cat_year', {'type_year': 'cumulative', 'year': 2020})
scenario.remove_set('cat_year', extra)`

**Comment by Chocooto** [comment]
I got the PRICE_EMISSION now! Thanks sooooo much for solving this problem and sharing so much information!!!
