### ISSUE TITLE
auto documentation of sets in the storage section of sets_maps_def.gms missing

### ISSUE THREAD

**Issue by volker-krey** [iiasa/message_ix#406]
Five sets and mapping sets in the storage section of sets_maps_def.gms come without auto documentation which needs to be added.

**Comment by khaeru** [comment]
No PR was opened for this by the feature freeze for v3.2.0, so we postpone to v3.3 (or later).

**Comment by khaeru** [comment]
@volker-krey on closer inspection, these were not missing. @behnam-zakeri had nicely included them inline in the existing tables, e.g. https://github.com/iiasa/message_ix/blob/a73cc3648672352c4f98e831df05ccc8a4da77ce/message_ix/model/MESSAGE/sets_maps_def.gms#L236-L241

I'll close this. But in #473, I will also move the definitions into the common blocks so that the documentation and definitions are nearby one another, for people trying to read the code directly.
