### ISSUE TITLE
Execution Error

### ISSUE THREAD

**Issue by AnnaSpedo** [iiasa/message_ix#411]
I developed a sectoral model in message_ix about maritime transport.
Everything works good untill in the "scenario.solve()" instance when I get the present error: 

CalledProcessError: Command '['gams', '"/Users/annaspedo/message/MESSAGE_run.gms"', '--in="/Users/annaspedo/message/data/MsgData_Shipping_green_trade_baseline.gdx"', '--out="/Users/annaspedo/message/output/MsgOutput_Shipping_green_trade_baseline.gdx"', '--iter="/Users/annaspedo/message/output/MsgIterationReport_Shipping_green_trade_baseline.gdx"', 'LogOption=4']' returned non-zero exit status 3.
 
And then from the Terminal the abort instance is like this: 
    *** Abort "The MESSAGEix version and the MESSAGE-scheme definition in the installed ixmp package do not match!"

Any suggestion on how to debug?

**Comment by khaeru** [comment]
@AnnaSpedo can you please…
- Give the output of `message-ix show-versions`
- Describe which version of message_ix you used to copy/produce the GAMS files `/Users/annaspedo/message/`

**Comment by Jihoon** [comment]
To me, it looks like a typical one you get when the model is infeasible. Have you gone through debugging steps by enabling slack variables in MESSAGE_master.gms?

**Comment by khaeru** [comment]
Related: iiasa/ixmp#383

**Comment by AnnaSpedo** [comment]
I debugged the issue and discovered that the execution error resulted from more nested issues. First of all, ixmp and gams solver where outdated and the license was expired. Then, there was actually an infeasibility due to too many constraints.

**Comment by khaeru** [comment]
@AnnaSpedo thanks for following up!

**Comment by panday1995** [comment]
> To me, it looks like a typical one you get when the model is infeasible. Have you gone through debugging steps by enabling slack variables in MESSAGE_master.gms?

Hi @Jihoon , I have encountered the same `non-zero exit status 3` error. Could your please teach me concretely how to  "_enabling slack variables in MESSAGE_master.gms_"? I didn't found any relavent information after I went through the documentation of message_ix, and I am new to GAMS
I am in 
`message_ix 3.1.0`
`python 3.6`
`GAMS 29.1`

In my case, I simply changed the horizon in the "Austrian energy system" example from `range(2010, 2041, 10)` to `range(2010, 2051, 10)`, and correspondingly changed `gdp = pd.Series([1.0, 1.21631, 1.4108, 1.63746], index=horizon)` to `gdp = pd.Series([1.0, 1.21631, 1.4108, 1.63746, 1.7777], index=horizon)`.

I assume no other parameters needs change since the codes worked when I changed the horizon from  `range(2010, 2041, 10)` to  `range(2010, 2031, 10)`

Thanks!

**Comment by Jihoon** [comment]
Hi @panday1995, I tested exact same changes you made to the same tutorial, To me, it runs without any problem. So I can say it is at least not an issue about the model specification/parametrization. Can there be any additional changes to the code?

**Comment by panday1995** [comment]
> Hi @panday1995, I tested exact same changes you made to the same tutorial, To me, it runs without any problem. So I can say it is at least not an issue about the model specification/parametrization. Can there be any additional changes to the code?

Hi @Jihoon , thanks for reply~ I rechecked other things, and found that it may because my GAMS license has expired similar to @AnnaSpedo .
