### ISSUE TITLE
installation instructions for rmessageix package

### ISSUE THREAD

**Issue by volker-krey** [iiasa/message_ix#412]
The installation instructions for the rmessageix package in general worked fine for me with the exception that the package created via `R CMD build rmessageix` ended being a `.tar.gz` instead of a `.zip` archive which resulted in the need to slightly adjust the second line of the instructions to `R CMD INSTALL rmessageix_*.tar.gz`. I used gitbash (based on the MINGW environment) for executing the installation instructions which could be a reason for this behavior. In any case, it could be useful to update the installation instructions accordingly.

**Comment by khaeru** [comment]
Thanks for recording this experience.

While working on #377, I found the rmessageix package is entirely empty except for the standard `reticulate` commands that import the Python `message_ix` package: https://github.com/iiasa/message_ix/blob/b99db755af736a27a800cdcb60878f08c03da7c1/rmessageix/R/init_rmessageix.R#L1-L22

I mentioned to @adrivinca that the code (e.g. the tutorials in R) seems to work even without the `adapt2ret()` function that was formerly included in rixmp/rmessageix. I think this is because reticulate/pandas improvements since then have obviated any need for this function.

To me, this raises the question of whether we want to trouble the user at all with the process of installing an R package, and instead simply say, "Install reticulate, then run `message_ix <- reticulate::import("message_ix")`."

We have not ever published rmessageix (or rixmp) on CRAN anyway. So, it could be deleted with no loss of functionality; this would be my preferred option.
One possible reason to retain it would be as a place for unit tests in R that thoroughly check all aspects of the functionality via R. But we have not had these in the past, nor made any plan to write them.

**Comment by adrivinca** [comment]
yes, agree with Paul. I also have been recently just using old R scripts by loading simply reticulate, and everything seem to work, including the solve function.
We could discuss if we want to get read of the package, while keeping the tutorials, update with the simple use of reticulate

**Comment by zsalimian** [comment]
I installed message-ix and then I verified the installation by the following command:
$message-ix --platform=default list

The system show me the following error:
![Untitled](https://user-images.githubusercontent.com/71164512/97264943-0d49a780-183b-11eb-9243-10296b0b78be.png)

How can I solve this issue?

**Comment by khaeru** [comment]
Hid an off-topic comment here from @zsalimian that was later refiled as #417.

**Comment by volker-krey** [comment]
I agree that in principle the `rmessageix` package can be removed, if instructions for setting up `reticulate` are provided. I recently converted old R code that was still relying on `rixmp` for generating the LED scenario to `rmessageix/reticulate` and had to set up the right `python` binary and `conda` environment using `reticulate` functionality to ensure that this would work (see example below).

```
# load required packages 
library(rmessageix)
# specify python binaries and environment under which messageix is installed
use_python("C:/.../anaconda3/envs/message_env/")
use_condaenv("message_env")
```

**Comment by khaeru** [comment]
No PR was opened for this by the feature freeze for v3.2.0, so we postpone to v3.3 (or later).
