### ISSUE TITLE
Errors while running the westeros_baseline

### ISSUE THREAD

**Issue by marek-iiasa** [iiasa/message_ix#497]
#### Expected result

error free output
#### Problem description

Two errors, see below
#### Versions
ixmp:        3.3.0
message_ix:  3.3.0
message_ix_models: None
message_data: None

click:       8.0.1
dask:        2021.06.0
genno:       installed
graphviz:    None
jpype:       1.2.1
… JVM path:  /Users/marek/anaconda3/envs/msg_env/lib/jli/libjli.dylib
openpyxl:    3.0.7
pandas:      1.2.4
pint:        0.17
xarray:      0.18.2
yaml:        5.4.1

iam_units:   installed
jupyter:     installed
matplotlib:  3.4.2
plotnine:    0.8.0
pyam:        0.11.0

GAMS:        35.2.0

python:      3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:15) 
[Clang 11.1.0 ]
python-bits: 64
OS:          Darwin
OS-release:  20.6.0
machine:     x86_64
processor:   i386
byteorder:   little
LC_ALL:      None
LANG:        None
LOCALE:      (None, 'UTF-8')
<details><summary>Output of <tt>message-ix show-versions</tt></summary>

```
--- GDXin=/Users/marek/anaconda3/envs/msg_env/lib/python3.9/site-packages/message_ix/model/data/MsgData_Westeros_Electrified_baseline.gdx
--- GDX File ($gdxIn) /Users/marek/anaconda3/envs/msg_env/lib/python3.9/site-packages/message_ix/model/data/MsgData_Westeros_Electrified_baseline.gdx
Run one of the following and paste the results here:
- 'message-ix show-versions' in a terminal, or
- 'import ixmp; ixmp.show_versions()' in a Python interpreter.

......

2021-08-10 11:01:21,270 ERROR at.ac.iiasa.ixmp.objects.Scenario:1691 - variable 'I' not found in gdx!
2021-08-10 11:01:21,270 ERROR at.ac.iiasa.ixmp.objects.Scenario:1691 - variable 'C' not found in gdx!
[I 11:02:40.122 NotebookApp] Saving file at /westeros_baseline.ipynb
```

</details>

**Comment by glatterf42** [comment]
Thanks for reporting these errors! They have been around for as long as I have been at IIASA and I don't know from where they originate. They do not seem to influence the actual solution process of a `Scenario`, though. My guess is that they come from within the ixmp source code, which we can't currently adapt. In that case, they should disappear with our eventual shift to ixmp4.

**Comment by khaeru** [comment]
> My guess is that they come from within the ixmp source code, which we can't currently adapt. In that case, they should disappear with our eventual shift to ixmp4.

ixmp-based code and message_ix can supply a `var_list` to the ixmp.JDBCBackend/ixmp_source that indicates a list of GAMS variables in the GDX output file to be read into the database along with other solution data. This is often used by colleagues who extend the MESSAGE formulation with additional variables.

However, when the lists are empty, the Java code uses certain embedded lists. I think the particular culprit is here:
https://github.com/iiasa/ixmp_source/blob/2ae0dcb6093e93e3047bf94b996da1e647ad701e/src/main/java/at/ac/iiasa/ixmp/modelspecs/MESSAGEspecs.java#L930-L951
…notice that "I" and "C" are present. The Java code has two classes, Scenario and MsgScenario, but doesn't have a "MacroScenario" or similar. So I suspect it uses this list always, even if it is reading a GDX file that was produced without using the MACRO GAMS code and thus would not have those variables.

I earlier transcribed mostly-complete lists of items (sets, parameters, variables, equations) into the message_ix source, here: https://github.com/iiasa/message_ix/blob/5c0b44f0118c3fcd361d1345d6a7cf1bd61658a0/message_ix/models.py#L957-L963 —these carefully distinguish items that are associated with the MESSAGE Model class from those associated with MACRO or MESSAGE_MACRO.

Probably one of the adjustments we will need to make in #894 is to always explicitly give the complete list of variables to be read from GDX, since by the principle of separation of concerns `ixmp` and `ixmp4` should not embed such lists.
