### ISSUE TITLE
Include Python version 3.10 and remove 3.6 in CI

### ISSUE THREAD

**Issue by LauWien** [iiasa/message_ix#532]
On the 4th of October Python 3.10 got released which lead to the failing of parts of our CI workflows. 
Among others the following issues and errors appeared: 

**nightly.yaml** / **lint.yaml**
_Install Python packages and dependencies_ / _Check typing with mypy_
```
Building wheel for numba (setup.py): finished with status 'error'
...
Building wheel for llvmlite (setup.py): finished with status 'error'
..."etc."
ModuleNotFoundError: No module named 'numpy'
..."etc."
Running setup.py install for llvmlite: finished with status 'error'
..."etc."
```

This might be due to the delayed adjustments of the packages we depend on related to the Python version 3.10.

A hot-fix got implemented in https://github.com/iiasa/message_ix/pull/529  where the usage of 3.10 in our CI was repressed. 
However this interferes with keeping our CI up to date.

The following ToDos arise:

- [ ] implement needed adjustments on our part to satisfy lint.yaml and nightly.yaml
- [ ] implement the version 3.10 into the pytest.yaml matrix [here ](https://github.com/iiasa/message_ix/blob/main/.github/workflows/pytest.yaml)
- [ ] remove support for 3.6, analogue to https://github.com/iiasa/ixmp/issues/434

**Comment by khaeru** [comment]
```
Building wheel for numba (setup.py): finished with status 'error'
Building wheel for llvmlite (setup.py): finished with status 'error'
```
These occur when there is no pre-compiled binary ("wheel") distribution for the package on PyPI. `pip` then downloads the source code and tries to compile the binaries itself. Usually the GitHub Actions runners lack some libraries or other tools necessary to do this, so it fails.

The things one can check to monitor when these become available:
- Look at the PyPI page and available downloads, e.g.:
  
  - https://pypi.org/project/llvmlite/0.37.0/#files
  - https://pypi.org/project/numba/0.54.1/#files
  
  These have a column "Python version" with values like "cp38" meaning "CPython 3.8"; this means the .whl file is binary-compatible with that version of Python. If there are no files for a specific version of Python (e.g. 3.10), then `pip` will attempt to compile the source from the .tar.gz, as mentioned above.
- The README on PyPI for `numba` specifically says "Python versions: 3.7-3.9", so that's a clear statement that 3.10 is not yet supported.
- The project's issue tracker. We can find
  - numba/llvmlite#740
  - numba/numba#7463 in turn pointing to numba/numba#7176 and numba/numba#7381

  So we probably can't expect support until those are closed and released.

**Comment by LauWien** [comment]
Thank you for the additional informations!
