### ISSUE TITLE
Enhance Westeros baseline tutorial to better serve testing purposes.

### ISSUE THREAD

**Issue by OFR-IIASA** [iiasa/message_ix#662]
In order to provide a better basis for testing some of the GAMS code, a possibility would be to make use of the Westeros tutorials. This means some of the core features of the baseline tutorial would need to be adapted.
This for example would include:
- timeperiods with varying duration to test the changes made in PR #654. (Alternatively, a test could be made to cover the `add_year` function, therefore introducing 5-year timesteps.)

**Comment by khaeru** [comment]
I would recommend we do not do this. A few reasons:
- The tutorial tests are flaky. Every time the nightly CI workflow runs, 1 to 2 of the 12 jobs fail due to time-outs in the nbclient package used to invoke the tutorials. This occurs not infrequently on PR branches, as well.
- The tutorial tests are (by far) the slowest part of the test suite.
- In #196, we already added [`message_ix.testing.make_westeros()`](https://docs.messageix.org/en/stable/api.html#message_ix.testing.make_westeros), and in the 3 years since have successfully used this in several tests, e.g. test_soft_constraint iiasa/message_ix@3e8d9b6d283d6055fa4af282c70f8fc59dc4e108.

Some other possibilities that would be significantly easier to maintain:
- Similar to the above example, write a fixture function that:
  1. Calls `make_westeros()` and then
  2. Makes some minimal changes to the resulting scenario.

  …then, use this fixture in tests.
  For the specific example of `duration_time`, the `model_generator()` function in test_feature_duration_time (added by @behnam-zakeri [here](https://github.com/iiasa/message_ix/blob/22de076315447a31352822633a66c1cabfc66e53/message_ix/tests/test_feature_duration_time.py#L15-L144)) could be revised in this way.
- Modify `make_westeros` itself, either by adding (an) optional argument(s) or changing the base behaviour. This would also ensure that other, existing tests that rely on make_westeros will pass on scenarios using these new/revised features.

**Comment by OFR-IIASA** [comment]
Thanks for comments Paul. I certainly wasnt aware that the tutorials fail so often.

In the meantime, I have made an adaptation of `make_westeros()` to add different `model_horizon`. This seems to do the job for the purpose of what I want to achieve.
